# Generated by Django 5.0.1 on 2024-01-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('가능한', '가능한'), ('거부된', '거부된')], max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
